<?php

use Core\Routing\URL;
//MENU EXPLICATION :  permet d'expliquer le titre d'un menu sous forme d'info bulle.
// ACTION : represente le nom de la route associé à une page; pour 

// TITLE-CODE =>
return[

    "accueil" => [
        "title" => "accueil",
        "icon" => "",
        "msg_page" => "",
        "menu_explication" => "",
        "full_url" => URL::link("accueil"),
        "action" => "accueil",
        "class" => "",
        "isActive" => "",
        "hasChildren" => false,
        "children" => [],
    ],

    "SCOLARITE" => [
        "title" => "Scolarité",
        "icon" => "fa fa-graduation-cap",
        "msg_page" => "",
        "menu_explication" => "",
        "full_url" => URL::link("eleve"),
        "action" => "eleve",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "Inscription" => [
                "title" => "Inscription",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("inscrire"),
                "action" => "inscrire",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "Versement" => [
                "title" => "Versement",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("versement"),
                "action" => "versement",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ELEVES_INSCRITS" => [
                "title" => "Elèves Inscrits",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("eleve"),
                "action" => "eleve",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "GESTION_CLASSES" => [
                "title" => "Gestion des Classes",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("versement"),
                "action" => "versement",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],

    "EMPLOI_TEMPS" => [
        "title" => "Emploi de temps",
        "icon" => "icon-calendar",
        "msg_page" => "",
        "menu_explication" => "",
        "full_url" =>  URL::link("accueil"),
        "action" => "accueil",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "BULLETIN" => [
            "title" => "bulletin",
            "icon" => "",
            "msg_page" => "",
            "menu_explication" => "",
            "full_url" => URL::link("bulletin"),
            "action" => "bulletin",
            "class" => "",
            "isActive" => "",
            "hasChildren" => false,
            "children" => [],
        ],],
    ],

    "BIBLIOTHEQUE" => [
        "title" => "Bibliothèque",
        "icon" => "fa fa-book",
        "msg_page" => "",
        "menu_explication" => "",
        "full_url" =>  URL::link("biblio_emprunt"),
        "action" => "biblio_emprunt",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "Emprunt/Restitution" => [
                "title" => "Emprunt",
                "icon" => "",
                "msg_page" => "Bienvenue à la section des pret des livres",
                "menu_explication" => "Bienvenue à la section des pret des livres",
                "full_url" =>  URL::link("biblio_emprunt"),
                "action" => "biblio_emprunt",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "GESTION_DOMAINE" => [
                "title" => "Gestion des domaines",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("domaine"),
                "action" => "domaine",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "GESTION_LIVRE" => [
                "title" => "Gestion des documents",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("document"),
                "action" => "document",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "GESTION_EXEMPLAIRE" => [
                "title" => "Gestion des exemplaires",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("exemplaire"),
                "action" => "exemplaire",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ETAT_DOCUMENT" => [
                "title" => "Etat d'un document",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("etat_document"),
                "action" => "etat_document",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

            "HISTORIQUE" => [
                "title" => "Historique",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("accueil"),
                "action" => "accueil",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],

    "BULLETIN" => [
        "title" => "Bulletin",
        "icon" => "icon-notebook",
        "msg_page" => "",
        "menu_explication" => "",
        "full_url" =>  URL::link("accueil"),
        "action" => "accueil",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "GENERER_BULLETIN" => [
                "title" => "Générer Bulletin",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("accueil"),
                "action" => "accueil",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ENREGISTRER_NOTE" => [
                "title" => "Enregistrer Note",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("accueil"),
                "action" => "accueil",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "FICHE_NOTE" => [
                "title" => "Fiche de Note",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("accueil"),
                "action" => "accueil",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "MODIFIER_NOTE" => [
                "title" => "Modifier Note",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("accueil"),
                "action" => "accueil",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "CONSULTER_NOTE" => [
                "title" => "Consulter Note",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("accueil"),
                "action" => "accueil",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],

    "CANTINE" => [
        "title" => "Cantine",
        "icon" => "fa fa-cutlery",
        "msg_page" => "",
        "menu_explication" => "",
        "full_url" =>  URL::link("accueil"),
        "action" => "accueil",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "ABONNEMENT" => [
                "title" => "Abonnement Cantine",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("abonnement_cantine"),
                "action" => "abonnement_cantine",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ENREGISTREMENT_MENU" => [
                "title" => "Enregistrement Menu",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("repas"),
                "action" => "repas",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "LISTE_ABONNEES" => [
                "title" => "Liste des Abonnées",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("cantine_liste"),
                "action" => "cantine_liste",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "CONSOMMATIONS" => [
                "title" => "Consommations",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("abonnement_cantine"),
                "action" => "abonnement_cantine",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "CONSOMMATIONS" => [
                "title" => "Statistique Cantine",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("cantine_accueil"),
                "action" => "cantine_accueil",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],

    "CLUB" => [
        "title" => "Club",
        "icon" => "fa fa-trophy",
        "msg_page" => "",
        "menu_explication" => "",
        "full_url" =>  URL::link("accueil"),
        "action" => "accueil",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "ABONNEMENT" => [
                "title" => "Abonnement Activité",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("accueil"),
                "action" => "accueil",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "CREATION_ACTIVITES" => [
                "title" => "Création Activités",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("activite"),
                "action" => "activite",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],

    "PERSONNEL" => [
        "title" => "Personnel",
        "icon" => "fa fa-users",
        "msg_page" => "",
        "menu_explication" => "",
        "full_url" =>  URL::link("accueil"),
        "action" => "accueil",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "ENREGISTREMENT_PERSONNEL" => [
                "title" => "Enregistrement Personnel",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("ajout_personnel"),
                "action" => "ajout_personnel",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

            "LISTE_PERSONNEL" => [
                "title" => "Liste Personnel",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("personnel_liste"),
                "action" => "",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

        ],
    ],

    "ENSEIGNEMENT" => [
        "title" => "Enseignement",
        "icon" => "fa fa-graduation-cap",
        "msg_page" => "",
        "menu_explication" => "",
        "full_url" =>  URL::link("accueil"),
        "action" => "accueil",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "AFFECTATION_CLASSE_MATIERE" => [
                "title" => "Affectation_Classe_Matière",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("affectation_classe_matiere"),
                "action" => "affectation_classe_matiere",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ENSEIGNANT_MATIERE_CLASSE" => [
                "title" => "Enseignant-Matière-Classe",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("cours"),
                "action" => "cours",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],


        "APERCUS" => [
            "title" => "Aperçus",
            "icon" => "ft-search",
            "msg_page" => "",
            "menu_explication" => "",
            "full_url" =>  URL::link("accueil"),
            "action" => "accueil",
            "class" => "",
            "isActive" => "",
            "hasChildren" => true,
            "children" => [
                "PAIEMENT_SALAIRE" => [
                    "title" => "Paiement Salaire",
                    "icon" => "",
                    "msg_page" => "",
                    "menu_explication" => "",
                    "full_url" =>  URL::link("accueil"),
                    "action" => "accueil",
                    "alt" => "",
                    "class" => "",
                    "isActive" => "",
                    "hasChildren" => false,
                    "children" => [],
                ],
                "ENREGISTREMENT_DEPENSE" => [
                    "title" => "Enregistrement Dépense",
                    "icon" => "",
                    "msg_page" => "",
                    "menu_explication" => "",
                    "full_url" =>  URL::link("accueil"),
                    "action" => "accueil",
                    "alt" => "",
                    "class" => "",
                    "isActive" => "",
                    "hasChildren" => false,
                    "children" => [],
                ],
            ],
        ],

    "CONFIGURATION" => [
        "title" => "Paramètrage",
        "icon" => "fa fa-cog",
        "msg_page" => "",
        "menu_explication" => "",
        "full_url" =>  URL::link("accueil"),
        "action" => "accueil",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "CYCLE" => [
                "title" => "Cycle",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("cycle"),
                "action" => "cycle",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "CLASSE" => [
                "title" => "Classe",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("classe"),
                "action" => "classe",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "SALLE_CLASSE" => [
                "title" => "Salle de Classe",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" =>  URL::link("salle_classe"),
                "action" => "salle_classe",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "PAYS" => [
                "title" => "Pays",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("pays"),
                "action" => "pays",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ANNEE_SCOLAIRE" => [
                "title" => "Année scolaire",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("annee_scolaire"),
                "action" => "annee_scolaire",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TRANCHE_SCOLAIRE" => [
                "title" => "Tranche scolaire",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("tranche_scolaire"),
                "action" => "tranche_scolaire",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TYPE_PAIEMENT" => [
                "title" => "Type paiement",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("type_paiement"),
                "action" => "type_paiement",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "STATUT_APPRENANT" => [
                "title" => "Statut apprenant",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("statut_apprenant"),
                "action" => "statut_apprenant",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "VERSEMENT_SCOLARITE" => [
                "title" => "Versement Scolarité",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("versement"),
                "action" => "versement",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TYPE_PENSION" => [
                "title" => "Type pension",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("type_pension"),
                "action" => "type_pension",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TRANCHE_SCOLAIRE" => [
                "title" => "Tranche scolaire",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("tranche_scolaire"),
                "action" => "tranche_scolaire",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TRANCHE_HORAIRE" => [
                "title" => "Tranche horaire",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("tranche_horaire"),
                "action" => "tranche_horaire",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "Eleve" => [
                "title" => "Elève",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("eleve"),
                "action" => "eleve",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "DISCPLINE" => [
                "title" => "Discpline",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("discipline"),
                "action" => "discipline",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

            "PENSION_CLASSE" => [
                "title" => "Pension classe",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("pension_classe"),
                "action" => "pension_classe",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

            "MATIERE" => [
                "title" => "Matière",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("matiere"),
                "action" => "matiere",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

            "REPAS" => [
                "title" => "Repas",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("repas"),
                "action" => "repas",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "SESSION" => [
                "title" => "Session",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("session"),
                "action" => "session",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            // "DOMAINE" => [
            //     "title" => "Domaine",
            //     "icon" => "",
            //     "msg_page" => "",
            //     "menu_explication" => "",
            //     "full_url" => URL::link("domaine"),
            //     "action" => "domaine",
            //     "alt" => "",
            //     "class" => "",
            //     "isActive" => "",
            //     "hasChildren" => false,
            //     "children" => [],
            // ],
            "PERIODE" => [
                "title" => "Periode",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("periode"),
                "action" => "periode",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TYPE_PERSONNEL" => [
                "title" => "Type_personnel",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("type_personnel"),
                "action" => "type_personnel",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ACTIVITE" => [
                "title" => "Activite",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("activite"),
                "action" => "activite",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TYPE_ACTIVITE" => [
                "title" => "Type d'activité",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("type_activite"),
                "action" => "type_activite",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "PERSONNEL_ACTIVITE" => [
                "title" => "Responsable personnel",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("personnel_activite"),
                "action" => "personnel_activite",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "INSCRIPTION_ACTIVITE" => [
                "title" => "Inscription activite",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("inscription_activite"),
                "action" => "inscription_activite",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ABONNEMENT_ACTIVITE" => [
                "title" => "Abonnement Activite",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("abonnement_activite"),
                "action" => "abonnement_activite",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "COURS" => [
                "title" => "Cours",
                "icon" => "",
                "msg_page" => "",
                "menu_explication" => "",
                "full_url" => URL::link("cours"),
                "action" => "cours",
                "alt" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],


];