<?php
use \Core\Routing\URL;

// TITLE-CODE =>
return[

    "ACCEUIL" => [
        "title" => "Acceuil",
        "icon" => "",
        "url" => "",
        "full_url" => URL::link("acceuil"),
        "action" => "",
        "class" => "",
        "isActive" => "",
        "hasChildren" => false,
        "children" => [],
    ],

    "SCOLARITE" => [
        "title" => "Scolarité",
        "icon" => "fa fa-graduation-cap",
        "url" => "",
        "full_url" => URL::link("eleve"),
        "action" => "",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "Inscription" => [
                "title" => "Inscription",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("inscrire"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "Versement" => [
                "title" => "Versement",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("versement"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ELEVES_INSCRITS" => [
                "title" => "Elèves Inscrits",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("eleve"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "GESTION_CLASSES" => [
                "title" => "Gestion des Classes",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("versement"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],

    "EMPLOI_TEMPS" => [
        "title" => "Emploi de temps",
        "icon" => "icon-calendar",
        "url" => "",
        "full_url" =>  URL::link("acceuil"),
        "action" => "",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "BULLETIN" => [
            "title" => "bulletin",
            "icon" => "",
            "url" => "",
            "full_url" => URL::link("bulletin"),
            "action" => "",
            "class" => "",
            "isActive" => "",
            "hasChildren" => false,
            "children" => [],
        ],],
    ],

    "BIBLIOTHEQUE" => [
        "title" => "Bibliothèque",
        "icon" => "fa fa-book",
        "url" => "",
        "full_url" =>  URL::link("acceuil"),
        "action" => "",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "Emprunt" => [
                "title" => "Emprunt",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("acceuil"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "Restitution" => [
                "title" => "Restitution",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("acceuil"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ENREGISTREMENT_LIVRE" => [
                "title" => "Enregistrement Livre",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("repas"),// erreur
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

            "HISTORIQUE" => [
                "title" => "Historique",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("acceuil"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],

    "BULLETIN" => [
        "title" => "Bulletin",
        "icon" => "icon-notebook",
        "url" => "",
        "full_url" =>  URL::link("acceuil"),
        "action" => "",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "GENERER_BULLETIN" => [
                "title" => "Générer Bulletin",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("acceuil"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ENREGISTRER_NOTE" => [
                "title" => "Enregistrer Note",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("acceuil"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "FICHE_NOTE" => [
                "title" => "Fiche de Note",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("acceuil"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "MODIFIER_NOTE" => [
                "title" => "Modifier Note",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("acceuil"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "CONSULTER_NOTE" => [
                "title" => "Consulter Note",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("acceuil"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],

    "CANTINE" => [
        "title" => "Cantine",
        "icon" => "fa fa-cutlery",
        "url" => "",
        "full_url" =>  URL::link("acceuil"),
        "action" => "",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "ABONNEMENT" => [
                "title" => "Abonnement",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("cantine"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ENREGISTREMENT_MENU" => [
                "title" => "Enregistrement Menu",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("repas"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "LISTE_ABONNEES" => [
                "title" => "Liste des Abonnées",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("cantine_liste"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "CONSOMMATIONS" => [
                "title" => "Consommations",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("acceuil"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],

    "CLUB" => [
        "title" => "Club",
        "icon" => "fa fa-trophy",
        "url" => "",
        "full_url" =>  URL::link("acceuil"),
        "action" => "",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "ABONNEMENT" => [
                "title" => "Abonnement",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("acceuil"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "CREATION_ACTIVITES" => [
                "title" => "Création Activités",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("activite"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],

    "PERSONNEL" => [
        "title" => "Personnel",
        "icon" => "fa fa-users",
        "url" => "",
        "full_url" =>  URL::link("acceuil"),
        "action" => "",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "ENREGISTREMENT_PERSONNEL" => [
                "title" => "Enregistrement Personnel",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("personnel"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

        ],
    ],

    "ENSEIGNEMENT" => [
        "title" => "Enseignement",
        "icon" => "fa fa-graduation-cap",
        "url" => "",
        "full_url" =>  URL::link("acceuil"),
        "action" => "",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "AFFECTATION_CLASSE_MATIERE" => [
                "title" => "Affectation_Classe_Matière",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("affectation_classe_matiere"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ENSEIGNANT_MATIERE_CLASSE" => [
                "title" => "Enseignant-Matière-Classe",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("cours"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],


        "APERCUS" => [
            "title" => "Aperçus",
            "icon" => "ft-search",
            "url" => "",
            "full_url" =>  URL::link("acceuil"),
            "action" => "",
            "class" => "",
            "isActive" => "",
            "hasChildren" => true,
            "children" => [
                "PAIEMENT_SALAIRE" => [
                    "title" => "Paiement Salaire",
                    "icon" => "",
                    "url" => "",
                    "full_url" =>  URL::link("acceuil"),
                    "action" => "",
                    "class" => "",
                    "isActive" => "",
                    "hasChildren" => false,
                    "children" => [],
                ],
                "ENREGISTREMENT_DEPENSE" => [
                    "title" => "Enregistrement Dépense",
                    "icon" => "",
                    "url" => "",
                    "full_url" =>  URL::link("acceuil"),
                    "action" => "",
                    "class" => "",
                    "isActive" => "",
                    "hasChildren" => false,
                    "children" => [],
                ],
            ],
        ],

    "CONFIGURATION" => [
        "title" => "Paramètrage",
        "icon" => "fa fa-cog",
        "url" => "",
        "full_url" =>  URL::link("acceuil"),
        "action" => "",
        "class" => "",
        "isActive" => "",
        "hasChildren" => true,
        "children" => [
            "CYCLE" => [
                "title" => "Cycle",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("cycle"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "CLASSE" => [
                "title" => "Classe",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("classe"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "SALLE_CLASSE" => [
                "title" => "Salle de Classe",
                "icon" => "",
                "url" => "",
                "full_url" =>  URL::link("salle_classe"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "PAYS" => [
                "title" => "Pays",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("pays"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ANNEE_SCOLAIRE" => [
                "title" => "Année scolaire",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("annee_scolaire"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TRANCHE_SCOLAIRE" => [
                "title" => "Tranche scolaire",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("tranche_scolaire"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TYPE_PAIEMENT" => [
                "title" => "Type paiement",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("type_paiement"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "STATUT_APPRENANT" => [
                "title" => "Statut apprenant",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("statut_apprenant"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "VERSEMENT_SCOLARITE" => [
                "title" => "Versement Scolarité",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("versement"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TYPE_PENSION" => [
                "title" => "Type pension",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("type_pension"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TRANCHE_SCOLAIRE" => [
                "title" => "Tranche scolaire",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("tranche_scolaire"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TRANCHE_HORAIRE" => [
                "title" => "Tranche horaire",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("tranche_horaire"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "Eleve" => [
                "title" => "Elève",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("eleve"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "DISCPLINE" => [
                "title" => "Discpline",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("discipline"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

            "PENSION_CLASSE" => [
                "title" => "Pension classe",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("pension_classe"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

            "MATIERE" => [
                "title" => "Matière",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("matiere"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],

            "REPAS" => [
                "title" => "Repas",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("repas"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "SESSION" => [
                "title" => "Session",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("session"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "DOMAINE" => [
                "title" => "Domaine",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("domaine"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "PERIODE" => [
                "title" => "Periode",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("periode"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TYPE_PERSONNEL" => [
                "title" => "Type_personnel",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("type_personnel"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ACTIVITE" => [
                "title" => "Activite",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("activite"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "TYPE_ACTIVITE" => [
                "title" => "Type d'activité",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("type_activite"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "PERSONNEL_ACTIVITE" => [
                "title" => "Responsable personnel",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("personnel_activite"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "INSCRIPTION_ACTIVITE" => [
                "title" => "Inscription activite",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("inscription_activite"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "ABONNEMENT_ACTIVITE" => [
                "title" => "Abonnement Activite",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("abonnement_activite"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
            "COURS" => [
                "title" => "Cours",
                "icon" => "",
                "url" => "",
                "full_url" => URL::link("cours"),
                "action" => "",
                "class" => "",
                "isActive" => "",
                "hasChildren" => false,
                "children" => [],
            ],
        ],
    ],


];