<?php
  $lang['number']		= 'Reference';
  $lang['date']			= 'Date de facturation';
  $lang['time']			= 'Temps de facturation';
  $lang['due']			= 'Date d\'échéance';
  $lang['to']			= 'Facturation à';
  $lang['from']			= 'Nos infos';
  $lang['product']		= 'Motif';
  $lang['qty']			= 'Quantité';
  $lang['vat']		    = 'Reste';
  $lang['price']		= 'Montant';
  $lang['discount']		= 'Remise';
  $lang['total']		= 'Total';
  $lang['page']			= 'Page';
  $lang['page_of']		= 'de';
?>